#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backend --config ~/.config/picom/picom.conf &
feh --bg-scale ~/.local/wallpaper/bocchi.jpg &
flameshot &
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config active_border_color "#414868"
bspc config focused_border_color "#414868"
bspc config normal_border_color "#24283B"
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
